# Generated by Django 4.2.4 on 2023-08-06 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_author_article_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_id',
            new_name='author',
        ),
    ]
